name: Commit on dispatch

on:
  repository_dispatch:
    types: [dispatched]

# github.event = {
#   "event_type": "dispatched",
#   "client_payload": {
#     "message": "foo"
#   }
# }

jobs:
  commit:
    permissions:
      contents: write

    env:
      LOGFILE: ./dispatched-logs.txt

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo ${{ github.event.client_payload.message }} >> $LOGFILE

      - name: Commit changes
        id: commit_changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: automated commit on repository_dispatch"
          file_pattern: $LOGFILE

      - name: Detect changes
        if: steps.commit_changes.outputs.changes_detected == 'true'
        run: echo "Changes detected"

      - name: Exit with error if no changes detected
        if: steps.commit_changes.outputs.changes_detected == 'false'
        run: exit 1
