name: Commit on dispatch

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to write to the log file"
        required: true
        default: "Update"

jobs:
  commit:
    permissions:
      contents: write

    env:
      LOGFILE: dispatched-logs.txt

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo ${{ inputs.message }} >> $LOGFILE

      - name: Commit changes
        id: commit_changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: automated commit on workflow_dispatch"
          file_pattern: $LOGFILE

      - run: echo "Changes detected"
        if: steps.commit_changes.outputs.changes_detected == 'true'

      - run: echo "No changes detected"
        if: steps.commit_changes.outputs.changes_detected == 'false'
